spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  jwt:
    secret-key: ${JWT_SECRET_KEY} #Hmac256
    expiration: 3_600_000 #1 hour

